version: '3.8'

services:
  app:
    build:
      context: .
      target: ${NODE_ENV:-development}
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./src:/app/src:delegated
      - ./nodemon.json:/app/nodemon.json
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: