version: '3.8'

services:

  backend:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - DB_HOST=website1-db
      - DB_USER=user1
      - DB_PASS=password1
      - DB_NAME=db1

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
